### ISSUE TITLE
Standard Library Tracking Issue

### ISSUE THREAD

**Issue by igaray** [lambdaclass/concrete#62]
The standard library that concrete offers should also be focused and minimal. 
The following modules should be included: 
- [ ] array: Utilities for the array primitive type.
- [ ] boxed: The Box<T> type for heap allocation.
- [ ] char: Utilities for the char primitive type.
- [ ] clone: The Clone trait for types that cannot be ‘implicitly copied’.
- [ ] cmp: Utilities for comparing and ordering values.
- [ ] collections: Collection types.
- [ ] convert: Traits for conversions between types.
- [ ] default: The Default trait for types with a default value.
- [ ] env: Inspection and manipulation of the process’s environment.
- [ ] error: Interfaces for working with Errors.
- [ ] f32: Constants for the f32 single-precision floating point type.
- [ ] f64: Constants for the f64 double-precision floating point type.
- [ ] ffi: Utilities related to FFI bindings.
- [ ] fmt: Utilities for formatting and printing Strings.
- [ ] fs: Filesystem manipulation operations.
- [ ] hash: Generic hashing support.
- [ ] io: Traits, helpers, and type definitions for core I/O functionality.
- [ ] iter: Composable external iteration.
- [ ] net: Networking primitives for TCP/UDP communication.
- [ ] option: Optional values.
- [ ] os: OS-specific functionality. Includes working with paths and processes. 
- [ ] result: Error handling with the Result type.
- [ ] string: A UTF-8–encoded, growable string.
- [ ] thread: Native threads.
- [ ] time: Temporal quantification.
- [ ] vec: A contiguous growable array type with heap-allocated contents.
